Changes to be committed: 	modified:   galore/__init__.py 	modified:   galore/cli/galore.py 	modified:   galore/cross_sections.py 	modified:   galore/formats.py 	modified:   test/test_plot.py
This is becasue "ImportError: cannot import name 'OrderedDict'
from 'collections.abc'" results from the previous commit.